name: webrtc

on:
  workflow_dispatch:
  push:
    branches: master
  pull_request:
    branches: master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test
    strategy:
      matrix:
        target: ['armv7-unknown-linux-gnueabihf', 'x86_64-unknown-linux-gnu']
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Install-ArmGcc
        run: sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
      - name: Init-Cargo
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --verbose --target ${{ matrix.target }}
      - name: Run tests
        run: cargo test --verbose --target ${{ matrix.target }}

  rustfmt_and_clippy:
    name: Check rustfmt style && run clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.55.0
          profile: minimal
          components: clippy, rustfmt
          override: true
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Check formating
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
